package com.firefly.experience.security.core.commands;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Command to authenticate a party using a device-generated biometric token.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BiometricLoginCommand {

    /** Signed biometric assertion token generated by the device. */
    private String biometricToken;

    /** Device information forwarded to the security center for session enrichment. */
    private String deviceInfo;
}
