name: Build Image

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  build-image:
    uses: firefly-oss/.github/.github/workflows/build-image.yml@main
    permissions:
      contents: read
      packages: write
    with:
      java-version: '25'
      web-module: 'exp-security-web'
    secrets: inherit
